# ========================================
# CONFIGURAZIONE PRIVATA FAi
# ========================================

# Partita IVA dell'emittente (usata nei file XML FatturaPA)
# Formato: IT + 11 cifre
PIVA_EMITTENTE = "IT12345678901"

# Credenziali PEC (usate per inviare le fatture via SDI)
PEC_USER = "nome-casella@pec.it"
PEC_PASS = "password-pec"

# Provider PEC: uno tra Aruba, PosteCert, Legalmail, Mailtrap
PEC_PROVIDER = "Mailtrap"

# ========================================
# SMTP opzionale (solo se usi invio email normale)
# ========================================
#EMAIL_MODE = "test"   # oppure "smtp"
#SMTP_HOST = "smtp.example.com"
#SMTP_PORT = "465"
#SMTP_USER = "user@example.com"
#SMTP_PASS = "password"
#SMTP_FROM = "no-reply@example.com"



SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "stefanofreyr@gmail.com"
SMTP_PASS = "afps hofx eigp tnaa"
FEEDBACK_RECIPIENT = "stefanofreyr@gmail.com"

# ========================================
# Altri segreti / configurazioni
# ========================================
# Qui puoi aggiungere altri parametri privati
# ACCESS_TOKEN = "..."
# API_KEY = "..."
MAILTRAP_TOKEN = "1db7f3de1d237e3080863f6568f411b8"

OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4o-mini"

GROQ_API_KEY = "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"

DEBUG_MODE = true
